### ISSUE TITLE
Injected built-in providers are not working

### ISSUE THREAD

**Issue by snortblt** [marcoturi/ionic2-boilerplate#19]
I used this project as a reference to add unit tests to my own project and ran into an issue where any methods called on injected dependencies from angular or ionic fail with the error "TypeError: undefined is not a constructor" (or "[methodname] is not a function" when running in Chrome). Even more strangely, I found that my own custom dependencies can be called successfully. Verified that dependencies are valid objects and appear to be of correct type.

As a sanity check, I tried cloning this project and simply added a  call to navCtrl.canGoBack() in the Home page constructor. This fails with the same error. Running node v6.8.1.

**Comment by marcoturi** [comment]
Hi @snortblt ! Please provide a forked repo with your code so I can give a look to the problem.

**Comment by snortblt** [comment]
Thanks! All I added is an additional test to home.page.spec.ts, which fails.

https://github.com/snortblt/ionic2-boilerplate/settings

**Comment by marcoturi** [comment]
That's because of the mock you are using. Let's look into the implementation of mockNavController:

`export declare const mockNavController: () => NavControllerBase;`

So basically it's returning the NavControllerBase, not instantiating it. This means for example that this assertion will be valid:

` expect(home.navCtrl).toBeDefined();`

but not the one that you wrote. So how to solve the issue ? Simply make your mock, for example extending the MockNav class that you can find [here](https://github.com/marcoturi/ionic2-boilerplate/blob/master/src/app/app.mock.spec.ts) and using it instead of mockNavController.

Hope it helps.

**Comment by snortblt** [comment]
Thanks @marcoturi!  I guess that should have been obvious to me. But as I got the same result with NavController and Nav instead of the mock I assumed there was another issue. Can you elaborate on why Nav produces the same results in a test environment but not in the production build?

**Comment by marcoturi** [comment]
> what is the purpose of the mocks provided in 'ionic-angular/util/mock-providers' if they aren't valid mocks?

It's a valid question. Honestly i don't know. They are not released to the public (ie no docs) and probably they are used for ionic internal purposes. But I'm not sure about this assumptions.

> Can you elaborate on why Nav produces the same results in a test environment but not in the production build? 

In general you should provide an instantiated object as useValue, not the object itself, i.e.:
`{provide: Nav, useValue: new MockNav()},` instead of `{provide: Nav, useValue: MockNav},`
